<!DOCTYPE html>
<html lang="fr">

<head>
    <link rel="shortcut icon" href="../assets/img/favicon/logo_ico.jpg" type="image/x-icon">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="NOFOLLOW, NOINDEX">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="views/css/normalize.css">
    <link rel="stylesheet" href="views/css/style.css">
    <title>Page de connexion Administrateur</title>
</head>

<body>
    <header class="login-header">
        <img class="logo" src="../assets/img/svg/logo/logo.svg" alt="Logo de la boutique">
        <h1>Administration</h1>
        <span>1.0</span>
    </header>
    <div class="container-login">
        <!-- Dynamic Content -->
        <?php require $template . ".phtml" ?>
    </div>
    <footer class="login-footer">
        <p>© By Laurent GUIGUES 2021-<?= date('Y') ?></p>
        <p>Tous droits réservés</p>
        <a class="linkedin" href="https://www.linkedin.com/in/laurent-guigues-25939b69/"><a class="github" href="https://github.com/LGUIGUES"></a>
    </footer>
    <script src="views/js/app.js"></script>
</body>

</html>