<!DOCTYPE html>
<html lang="fr">

<head>
    <link rel="shortcut icon" href="../assets/img/favicon/logo_ico.jpg" type="image/x-icon">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="NOFOLLOW, NOINDEX">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>
    <link rel="stylesheet" type="text/css" href="views/css/normalize.css">
    <link rel="stylesheet" href="views/css/style.css">
    <title>Administration de la boutique</title>
</head>

<body>
    <header class="header-dashboard">
        <nav class="nav-header">
            <span id="menuClosed" class="icon-burger-menu-closed"></span>
            <div class="burger-menu">
                <div class="title-before-sub-menu"><a href="index.php?page=dashBoard">Tableau de bord</a></div>
                <div class="accordion" id="accordionSubMenu">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button collapsed sub-menu-title-orders" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                Commandes
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionSubMenu">
                            <div class="accordion-body">
                                <ul>
                                    <li><a href="index.php?page=viewOrders">Commandes</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button collapsed sub-menu-title-bookings" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Ateliers
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionSubMenu">
                            <div class="accordion-body">
                                <ul>
                                    <li><a href="index.php?page=viewWorkshop">Ateliers</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed sub-menu-title-products" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Catalogue
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionSubMenu">
                            <div class="accordion-body">
                                <ul>
                                    <li><a href="index.php?page=category">Catégories</a></li>
                                    <li><a href="index.php?page=viewProducts">Produits</a></li>
                                    <li><a href="index.php?page=gallery">Galerie Images</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingFour">
                            <button class="accordion-button collapsed sub-menu-title-customers" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                Clients
                            </button>
                        </h2>
                        <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionSubMenu">
                            <div class="accordion-body">
                                <ul>
                                    <li><a href="index.php?page=viewUsers">Clients</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingFive">
                            <button class="accordion-button collapsed sub-menu-title-messages" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                Messages
                            </button>
                        </h2>
                        <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionSubMenu">
                            <div class="accordion-body">
                                <ul>
                                    <li><a href="index.php?page=messaging">Messages</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingSix">
                            <button class="accordion-button collapsed sub-menu-title-display" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                Apparence
                            </button>
                        </h2>
                        <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingSix" data-bs-parent="#accordionSubMenu">
                            <div class="accordion-body">
                                <ul>
                                    <li><a href="index.php?page=configurationHomePage">Page d'accueil</a></li>
                                    <li><a href="index.php?page=configurationEvent">Bloc évènements</a></li>
                                    <li><a href="index.php?page=contentPages">Pages de contenu</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingSeven">
                            <button class="accordion-button collapsed sub-menu-title-parameters" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                                Configuration
                            </button>
                        </h2>
                        <div id="collapseSeven" class="accordion-collapse collapse" aria-labelledby="headingSeven" data-bs-parent="#accordionSubMenu">
                            <div class="accordion-body">
                                <ul>
                                    <li><a href="index.php?page=configuration">Général</a></li>
                                    <li><a href="index.php?page=configuration#company">Entreprise</a></li>
                                    <li><a href="index.php?page=configuration#social-networks">Réseaux Sociaux</a></li>
                                    <li><a href="index.php?page=configuration#workHours">Horaires d'ouvertures</a></li>
                                    <li><a href="index.php?page=configuration#services">Vos services</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="title-after-sub-menu"><a href="index.php?page=disconnectionAdmin">Déconnexion</a></div>
                <div class="burger-menu-copyright">
                    <p class="align-center">&copy;<a href="https://www.laurentguigues.fr">Laurent GUIGUES</a></p>
                    <p class="align-center">2021-<?= date('Y') ?></p>
                    <p class="align-center">Tous droits réservés</p>
                    <a class="linkedin" href="https://www.linkedin.com/in/laurent-guigues-25939b69/"></a><a class="github" href="https://github.com/LGUIGUES"></a>
                </div>
            </div>
            <div class="left-block">
                <a href="index.php?action=dashBoard">
                    <img class="logo-nav" src="../assets/img/svg/logo/logo.svg" alt="Logo">
                </a>
                <span class="shop-version">1.0</span>
            </div>
            <div class="right-block">
                <a href="../../index.php" target="_blank"><i class="fas fa-eye"><span class="view-shop"></span><span class="view-shop-txt">Ma boutique</span></i></a>
                <a id="modalNotifications" href="#">
                    <i class="far fa-bell notification"></i>
                    <div class="circle-notification">
                        <span id="totalNotification" class="qty"></span>
                    </div>
                </a>
                <a href="index.php?page=profil"><i class="fas fa-user-circle account"></i></a>
            </div>
        </nav>
        <div class="modal-notifications">
            <div class="notifications-title">
                <a id="messageNotification" href="#targetNotification">Messages</a>
                <a id="customerNotification" href="#targetNotification">Clients</a>
                <a id="orderNotification" href="#targetNotification">Commandes</a>
            </div>
            <div id="targetNotifications"></div>
        </div>
    </header>
    <main class="content">
        <div class="left-menu">
            <div class="title-before-sub-menu"><a href="index.php?page=dashBoard">Tableau de bord</a></div>
            <div class="accordion" id="accordionSubMenuLapTop">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="laptopheadingOne">
                        <button class="accordion-button collapsed sub-menu-title-orders" type="button" data-bs-toggle="collapse" data-bs-target="#laptopcollapseOne" aria-expanded="false" aria-controls="collapseOne">
                            Commandes
                        </button>
                    </h2>
                    <div id="laptopcollapseOne" class="accordion-collapse collapse" aria-labelledby="laptopheadingOne" data-bs-parent="#accordionSubMenu">
                        <div class="accordion-body">
                            <ul>
                                <li><a href="index.php?page=viewOrders">Commandes</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="laptopheadingTwo">
                        <button class="accordion-button collapsed sub-menu-title-bookings" type="button" data-bs-toggle="collapse" data-bs-target="#laptopcollapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Ateliers
                        </button>
                    </h2>
                    <div id="laptopcollapseTwo" class="accordion-collapse collapse" aria-labelledby="laptopheadingTwo" data-bs-parent="#accordionSubMenu">
                        <div class="accordion-body">
                            <ul>
                                <li><a href="index.php?page=viewWorkshop">Ateliers</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="laptopheadingThree">
                        <button class="accordion-button collapsed sub-menu-title-products" type="button" data-bs-toggle="collapse" data-bs-target="#laptopcollapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Catalogue
                        </button>
                    </h2>
                    <div id="laptopcollapseThree" class="accordion-collapse collapse" aria-labelledby="laptopheadingThree" data-bs-parent="#accordionSubMenu">
                        <div class="accordion-body">
                            <ul>
                                <li><a href="index.php?page=category">Catégories</a></li>
                                <li><a href="index.php?page=viewProducts">Produits</a></li>
                                <li><a href="index.php?page=gallery">Galerie Images</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="laptopheadingFour">
                        <button class="accordion-button collapsed sub-menu-title-customers" type="button" data-bs-toggle="collapse" data-bs-target="#laptopcollapseFour" aria-expanded="false" aria-controls="collapseFour">
                            Clients
                        </button>
                    </h2>
                    <div id="laptopcollapseFour" class="accordion-collapse collapse" aria-labelledby="laptopheadingFour" data-bs-parent="#accordionSubMenu">
                        <div class="accordion-body">
                            <ul>
                                <li><a href="index.php?page=viewUsers">Clients</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="laptopheadingFive">
                        <button class="accordion-button collapsed sub-menu-title-messages" type="button" data-bs-toggle="collapse" data-bs-target="#laptopcollapseFive" aria-expanded="false" aria-controls="collapseFive">
                            Messages
                        </button>
                    </h2>
                    <div id="laptopcollapseFive" class="accordion-collapse collapse" aria-labelledby="laptopheadingFive" data-bs-parent="#accordionSubMenu">
                        <div class="accordion-body">
                            <ul>
                                <li><a href="index.php?page=messaging">Messages</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="laptopheadingSix">
                        <button class="accordion-button collapsed sub-menu-title-display" type="button" data-bs-toggle="collapse" data-bs-target="#laptopcollapseSix" aria-expanded="false" aria-controls="collapseSix">
                            Apparence
                        </button>
                    </h2>
                    <div id="laptopcollapseSix" class="accordion-collapse collapse" aria-labelledby="laptopheadingSix" data-bs-parent="#accordionSubMenu">
                        <div class="accordion-body">
                            <ul>
                                <li><a href="index.php?page=configurationHomePage">Page d'accueil</a></li>
                                <li><a href="index.php?page=configurationEvent">Bloc évènements</a></li>
                                <li><a href="index.php?page=contentPages">Pages de contenu</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="laptopheadingSeven">
                        <button class="accordion-button collapsed sub-menu-title-parameters" type="button" data-bs-toggle="collapse" data-bs-target="#laptopcollapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                            Configuration
                        </button>
                    </h2>
                    <div id="laptopcollapseSeven" class="accordion-collapse collapse" aria-labelledby="laptopheadingSeven" data-bs-parent="#accordionSubMenu">
                        <div class="accordion-body">
                            <ul>
                                <li><a href="index.php?page=configuration">Général</a></li>
                                <li><a href="index.php?page=configuration#company">Entreprise</a></li>
                                <li><a href="index.php?page=configuration#social-networks">Réseaux Sociaux</a></li>
                                <li><a href="index.php?page=configuration#workHours">Horaires d'ouvertures</a></li>
                                <li><a href="index.php?page=configuration#services">Vos services</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="title-after-sub-menu"><a href="index.php?page=disconnectionAdmin">Déconnexion</a></div>
            <div class="copyright">
                <p class="align-center">&copy;<a href="https://www.laurentguigues.fr">Laurent GUIGUES</a></p>
                <p class="align-center">2021-<?= date('Y') ?></p>
                <p class="align-center">Tous droits réservés</p>
                <a class="linkedin" href="https://www.linkedin.com/in/laurent-guigues-25939b69/"></a><a class="github" href="https://github.com/LGUIGUES"></a>
            </div>
        </div>
        <div class="dynamic-content">
            <?php require $template . ".phtml" ?>
        </div>
    </main>
    <footer class="footer-dashboard">
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="views/js/menu.js"></script>
    <script src="views/js/app.js"></script>
    <script src="views/js/notifications.js"></script>
</body>

</html>