<?php if (!isset($_SESSION["idAdmin"])) :
    header('location:../../../../index.php');
    exit();
endif; ?>
<article>
    <h2>Gestion de vos messages clients et invités</h2>
    <p>Vous pouvez gérer ici les messages de vos clients ou des contacts</p>
    <?php if (array_key_exists('errors', $_SESSION)) : ?>
        <div class="errors">
            <?= '<ul>' . implode('<li>', $_SESSION['errors']) . '</ul>'; ?>
        </div>
    <?php endif; ?>
    <?php if (array_key_exists('success', $_SESSION)) : ?>
        <div class="success">
            <?= '<ul>' . implode('<li>', $_SESSION['success']) . '</ul>'; ?>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="table-responsive">
            <table>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nom du client</th>
                        <th>Email</th>
                        <th>Messages</th>
                        <th>Dernier message</th>
                        <th colspan="1"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($messages as $message) : ?>
                        <tr>
                            <td><?= htmlspecialchars($message['id_thread_user']) ?>
                                <input type="hidden" name="idThread" value="<?= htmlspecialchars($message['id_thread_user']) ?>" />
                            </td>
                            <td><?= !empty($message['id_user']) ? htmlspecialchars($message['firstname']) . ' ' . htmlspecialchars($message['lastname']) : '--' ?></td>
                            <td><?= htmlspecialchars($message['email']) ?></td>
                            <td><a href="index.php?page=detailsMessage&idThread=<?= htmlspecialchars($message['id_thread_user']) ?>" title="<?= htmlspecialchars($message['messages']) ?>"><?= htmlspecialchars(substr($message['messages'], 0, 40) . "...") ?></a></td>
                            <td><?= htmlspecialchars(date('d-m-y', strtotime($message['date_add']))) ?></td>
                            <td><a class="btn-view" href="index.php?page=detailsMessage&idThread=<?= htmlspecialchars($message['id_thread_user']) ?>"><i class="fas fa-eye"></i></a></td>
                        </tr>
                    <?php endforeach; ?>
            </table>
        </div>
    </div>
</article>
<?php
unset($_SESSION['errors']);
unset($_SESSION['success']);
?>