<?php if (!isset($_SESSION["idAdmin"])) :
    header('location:../../../../index.php');
    exit();
endif; ?>
<article>
    <h2>Création d'une page de contenu</h2>
    <p>Créez votre page de contenu en suivant les étapes ci-dessous.</p>
    <nav class="breadcrumb">
        <a class="first" href="index.php?page=dashBoard">Retour Tableau de bord</a><span class="chevron">&gt;</span><a href="index.php?page=contentPages">Retour gestion des pages de contenu</a><span class="chevron">&gt;</span><span class="current-page">Création d'une page de contenu</span>
    </nav>
    <?php if (array_key_exists('errors', $_SESSION)) : ?>
        <div class="errors">
            <?= '<ul>' . implode('<li>', $_SESSION['errors']) . '</ul>'; ?>
        </div>
    <?php endif; ?>
    <?php if (array_key_exists('success', $_SESSION)) : ?>
        <div class="success">
            <?= '<ul>' . implode('<li>', $_SESSION['success']) . '</ul>'; ?>
        </div>
    <?php endif; ?>
    <p>Choisissez le bloc dans lequels vous voulez mettre le lien.</p>
    <form action="index.php?page=createPage" method="POST">
        <fieldset>
            <label class="required" for="blockLinkPage">Choix du bloc</label>
            <select name="blockLinkPage" id="blockLinkPage">
                <?php foreach ($blocksLocation as $blockLocation) : ?>
                    <option value="<?= htmlspecialchars($blockLocation['id_location']) ?>"><?= htmlspecialchars($blockLocation['name_location']) ?></option>
                <?php endforeach; ?>
            </select>
            <label class="required" for="activePage">Activer la page</label>
            <select name="activePage" id="activePage">
                <option value="1">Oui</option>
                <option value="0">Non</option>
            </select>
            <p>Choisissez le titre de votre page</p>
            <label class="required" for="titleContent">Titre de la page</label>
            <input type="text" name="titleContent" id="titleContent" value="<?= isset($_SESSION['formData']['titleContent']) ? $_SESSION['formData']['titleContent'] : '' ?>" size="40" required>
            <label for="textContent">Votre contenu</label>
            <textarea name="textContent" id="textContent" cols="80" rows="60" required>
            <?= isset($_SESSION['formData']['textContent']) ? $_SESSION['formData']['textContent'] : '' ?>
            </textarea>
            <script>
                CKEDITOR.replace('textContent');
            </script>
        </fieldset>
        <div class="btn-form">
            <button class="btn-form-submit" id="btn-form-submit" type="submit" name="submit">Enregistrer</button>
            <a class="btn-form-cancel" href="index.php?page=contentPages">Annuler</a>
        </div>
    </form>
</article>
<?php
unset($_SESSION['formData']);
unset($_SESSION['errors']);
unset($_SESSION['success']);
?>