<?php if (!isset($_SESSION["idUser"])) :
    header('location:../../../../index.php');
    exit();
endif; ?>
<!-- Affichage page gestion réservations ateliers floral utilisateur -->
<article>
    <div class="row account-user">
        <h2>Vos ateliers fleurs</h2>
        <p>Vous pouvez vous réserver ou supprimer un cours depuis cet espace. Attention : Vous ne pouvez pas vous désinscrire d'un cours déjà confirmé.</p>
        <nav class="breadcrumb">
            <a class="first" href="index.php" title="Accueil">Accueil</a><span class="chevron">&gt;</span><a href="index.php?page=customer_account" title="Retour à votre espace personnel">Retour à votre espace personnel</a><span class="chevron">&gt;</span><span class="current-page">Vos ateliers fleurs</span>
        </nav>
        <?php if (array_key_exists('errors', $_SESSION)) : ?>
            <div class="errors">
                <?= '<ul>' . implode('<li>', $_SESSION['errors']) . '</ul>'; ?>
            </div>
        <?php endif; ?>
        <?php if (array_key_exists('success', $_SESSION)) : ?>
            <div class="success"><?= '<ul>' . implode('<li>', $_SESSION['success']) . '</ul>'; ?>
            </div>
        <?php endif; ?>
        <div class="actions">
            <a class="action-button" href="index.php?page=registrationFlowerWorkshop" title="S'inscrire à un cours floral">S'inscrire à un cours floral</a>
        </div>
        <div class="row">
            <div class="table-responsive flowers-works">
                <table>
                    <thead>
                        <tr>
                            <th>Jour</th>
                            <th>Horaire du cours</th>
                            <th>Statut</th>
                            <th>Confirmé</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($flowersWorkshopUser as $flowerWorkshopUser) : ?>
                            <tr>
                                <td><?= htmlspecialchars($flowerWorkshopUser['name_shop_day']) . ' ' . htmlspecialchars(date('d-m', strtotime($flowerWorkshopUser['work_date']))) ?></td>
                                <td><?= htmlspecialchars($flowerWorkshopUser['time_start']) . 'h à ' . htmlspecialchars($flowerWorkshopUser['time_end']) . 'h' ?></td>
                                <td><?= !empty($flowerWorkshopUser['canceled'] == 0) ? 'En cours' : 'Annulé' ?></td>
                                <td><?= !empty($flowerWorkshopUser['confirmed'] == 0) ? 'Non' : 'Oui' ?></td>
                                <?php if ($flowerWorkshopUser['confirmed'] != 1) : ?>
                                    <td>
                                        <form class="button" action="index.php?page=deleteFlowerWorkshop" method="POST">
                                            <input type="hidden" name="idWork" value="<?= htmlspecialchars($flowerWorkshopUser['id_work']) ?>" />
                                            <button class="btn-delete" name="submit" type="submit"><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                    </td>
                                <?php else : ?>
                                    <td>
                                        <button class="btn-disabled"><i class="fas fa-trash-alt"></i></button>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</article>
<?php
unset($_SESSION['errors']);
unset($_SESSION['success']);
?>