<?php if(!isset($_SESSION["idAdmin"])) :
    header('location:../../../../index.php');
    exit();
endif; ?>
<article>
    <h2>Gestion des cours floraux</h2>
    <p>Vous pouvez suivre les réservations aux cours floraux. Ajouter, modifier ou supprimer des cours.</p>
    <nav class="breadcrumb">
    <a class="first" href="index.php?page=dashBoard">Retour Tableau de bord</a><span class="chevron">&gt;</span><span class="current-page">Gestion des cours floraux</span>
    </nav>    
    <?php if(array_key_exists('errors',$_SESSION)) : ?>
        <div class="errors">
            <?= '<ul>'.implode('<li>',$_SESSION['errors']).'</ul>'; ?>
        </div>
    <?php endif; ?>
    <?php if(array_key_exists('success',$_SESSION)) : ?>
        <div class="success">
            <?= '<ul>'.implode('<li>',$_SESSION['success']).'</ul>'; ?>
        </div>
    <?php endif; ?>
    <div class="actions">
        <a class="action-button" href="index.php?page=createFlowerWorkshop">Ajouter un cours floral</a>                     
    </div>    
    <div class="row">
        <h3>La liste de vos cours avec des participants</h3>
        <div class="table-responsive">
            <table>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Date du cours</th>                        
                        <th>Horaires</th>                        
                        <th>Participants max.</th>
                        <th>Inscrits</th>
                        <th>Places disponibles</th>
                        <th>Activé</th>
                        <th>Statut</th>
                        <th colspan="2">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($flowersWorkshopReservations as $flowerWorkshopReservation) :?>                    
                <tr>
                    <td><?= htmlspecialchars($flowerWorkshopReservation['id_work']) ?></td>                    
                    <td><?= htmlspecialchars(date('d-m-y', strtotime($flowerWorkshopReservation['work_date'] ))) ?></td>                                       
                    <td><?= htmlspecialchars($flowerWorkshopReservation['time_start']).'h - '.htmlspecialchars($flowerWorkshopReservation['time_end']) ?>h</td>                    
                    <td><?= htmlspecialchars($flowerWorkshopReservation['max_space']) ?></td>
                    <td><?= htmlspecialchars($flowerWorkshopReservation['guests']) ?></td>
                    <td><?= htmlspecialchars($flowerWorkshopReservation['max_space'] - htmlspecialchars($flowerWorkshopReservation['guests'])) ?></td>
                    <td><?= !empty(htmlspecialchars($flowerWorkshopReservation['active'] == 1)) ? 'Oui' : 'Non' ?></td>
                    <td><?= !empty(htmlspecialchars($flowerWorkshopReservation['cancel'] == 0)) ? 'En cours' : 'Annulé' ?></td>                    
                    <td><a class="btn-edit" href="index.php?page=editFlowerWorkshopDetails&idWork=<?= htmlspecialchars($flowerWorkshopReservation['id_work']) ?>"><i class="fas fa-pencil-alt"></i></a></td>                    
                    <td><a class="btn-view" href="index.php?page=viewFlowerWorkshopDetails&idWork=<?= htmlspecialchars($flowerWorkshopReservation['id_work']) ?>"><i class="fas fa-eye"></i></a></td>     
                </tr>                    
                <?php endforeach; ?> 
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <h3>La liste de vos cours sans participants</h3>
        <div class="table-responsive">
            <table>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Date du cours</th>                        
                        <th>Horaires</th>                        
                        <th>Participants max.</th>
                        <th>Inscrits</th>
                        <th>Places disponibles</th>
                        <th>Activé</th>
                        <th colspan="3">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($flowersWorkshop as $flowerWorkshop) :?>                    
                <tr>
                    <td><?= htmlspecialchars($flowerWorkshop['id_work']) ?></td>                    
                    <td><?= htmlspecialchars(date('d-m-y', strtotime($flowerWorkshop['work_date'] ))) ?></td>                                       
                    <td><?= htmlspecialchars($flowerWorkshop['time_start']).'h - '.htmlspecialchars($flowerWorkshop['time_end']) ?>h</td>                    
                    <td><?= htmlspecialchars($flowerWorkshop['max_space']) ?></td>
                    <td><?= htmlspecialchars($flowerWorkshop['max_space'] - htmlspecialchars($flowerWorkshop['space_available'])) ?></td>
                    <td><?= htmlspecialchars($flowerWorkshop['space_available']) ?></td>
                    <td><?= !empty(htmlspecialchars($flowerWorkshop['active'] == 1)) ? 'Oui' : 'Non' ?></td>                    
                    <td><a class="btn-edit" href="index.php?page=editFlowerWorkshopDetails&idWork=<?= htmlspecialchars($flowerWorkshop['id_work']) ?>"><i class="fas fa-pencil-alt"></i></a></td>
                    <td>
                        <form action="index.php?page=deleteFlowerWorkshop" method="POST">
                            <input type="hidden" name="idWork" value="<?= htmlspecialchars($flowerWorkshop['id_work']) ?>">
                            <button class="btn-delete" name="submit" type="submit"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>                    
                <?php endforeach; ?> 
                </tbody>
            </table>
        </div>
    </div>      
</article>
<?php
unset($_SESSION['errors']);
unset($_SESSION['success']);
?>    