<!-- Affiche page mot de passe oublié -->
<article>
    <div class="row form">
        <h2>Récupération de mot de passe</h2>
        <?php if(array_key_exists('errors', $_SESSION)) : ?>
            <div class="errors">
                <?= '<ul>'.implode('<li>',$_SESSION['errors']).'</ul>'; ?>
            </div>
            <?php endif; ?>
        <?php if(isset($_SESSION['success'])) : ?>
            <div class="success"><?= htmlspecialchars($_SESSION['success']) ?></div>
        <?php endif; ?>
        <form action="index.php?page=forgot_password" method="POST">
            <fieldset>
                <p>Merci de nous indiquer l'adresse e-mail utilisée lors de la création de votre compte. Un lien de réinitialisation va vous être envoyé.</p>
                <label class="required" for="email">Adresse e-mail : </label>
                <?php if(isset($_SESSION['formData']['email'])) : ?>
                <input type="email" name="email" id="email" value="<?= htmlspecialchars($_SESSION['formData']['email']) ?>" required/>
                <?php else : ?>
                    <input type="email" name="email" id="email" placeholder="votre@email.fr" required/>
                <?php endif; ?>           
            </fieldset>
            <div class="btn-form">
                <button class="btn-form-submit" id="btn-form-submit" type="submit" name="submit">Envoyer</button>
                <button class="btn-form-cancel" type="reset">Effacer</button>
            </div>
        </form>
        <a class="forgot-password text-align-center" href="index.php?page=authentification" title="Retour à la connexion">Retour à la connexion</a>
    </div>    
</article>
<?php
unset($_SESSION['formData']);
unset($_SESSION['errors']);
unset($_SESSION['success']);
?>