<!-- Affichage page des évènements -->
<article>
    <h2 class="events-title-page">Evènements du moment chez votre fleuriste</h2>
    <div class="events-page">
        <?php foreach ($shopEvents as $event) : ?>
            <?php if (isset($event['id_event']) && $event['active'] != 0) : ?>
                <div class="events">
                    <div class="event-img">
                        <img class="img-event" src="www/assets/img/event/large/<?= htmlspecialchars($event['img_event_large']) ?>" alt="<?= htmlspecialchars($event['title_shop_event']) ?>">
                        <div class="customize-event">
                            <h2 class="title-event title-page-events"><?= htmlspecialchars($event['title_shop_event']) ?></h2>
                            <div class="description-event description-page-events">
                                <?= strip_tags($event['description_shop_event'], $tags) ?>
                            </div>
                            <div class="date-event date-page-events">
                                <h2>Du <?= htmlspecialchars(date('d-m-Y', strtotime($event['event_start']))) ?> au <?= htmlspecialchars(date('d-m-Y', strtotime($event['event_end']))) ?></h2>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</article>