<?php if(!isset($_SESSION["idUser"])) :
    header('location:../../../../index.php');
    exit();
endif; ?>
<!-- Affichage des détails d'une commande utilisateur -->
<article>
    <div class="row account-user">     
        <h2>Détails de la commande</h2>
        <div class="order-number">
            <p class="text-align-center">Commande N° <?= htmlspecialchars($idOrder) ?> du <?= htmlspecialchars(date('d-m-y', strtotime($dateOrder))) ?></p>
        </div>        
        <nav class="breadcrumb">
            <a class="first" href="index.php" title="Accueil">Accueil</a><span class="chevron">&gt;</span><a href="index.php?page=customer_account" title="Retour à votre espace personnel">Retour à votre espace personnel</a><span class="chevron">&gt;</span><a href="index.php?page=myOrders" title="Retour à vos commandes">Retour à vos commandes</a><span class="chevron">&gt;</span><span class="current-page">Détails de la commande</span>
        </nav>    
        <?php if(array_key_exists('errors', $_SESSION)) : ?>
            <div class="errors">
                <?= '<ul>'.implode('<li>',$_SESSION['errors']).'</ul>'; ?>
            </div>
        <?php endif; ?>
        <?php if(array_key_exists('success', $_SESSION)) : ?>
            <div class="success">
                <?= '<ul>'.implode('<li>',$_SESSION['success']).'</ul>'; ?>
        </div>
        <?php endif; ?>
        <div class="row-order">            
            <div class="row">
                <div class="table-responsive status-order">
                    <table>
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Etat</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($orderHistory as $detailsHistory) : ?>
                            <tr>
                                <td><?= htmlspecialchars($detailsHistory['date_add']) ?></td>
                                <td><?= htmlspecialchars($detailsHistory['name_status']) ?></td>                        
                            </tr>
                            <?php endforeach; ?>
                        </tbody>                
                    </table>
                </div>                
            </div>
            <div class="order-delivery">
                <p>Livraison : <?= htmlspecialchars($delivery) ?></p>
            </div>
            <div class="order-payment">
                <p>Mode de paiement : <?= htmlspecialchars($payment) ?></p>
            </div>           
            <div class="address-order">
                <p>Adresse de Facturation</p>
                <address class="row card-address">
                    <p><?= htmlspecialchars($addressUser['lastname']).' '.htmlspecialchars($addressUser['firstname']) ?></p>
                    <p><?= htmlspecialchars($addressUser['company']) ?></p>
                    <p><?= htmlspecialchars($addressUser['addresse']) ?></p>
                    <p><?= htmlspecialchars($addressUser['address_comp']) ?></p>
                    <p><?= htmlspecialchars($addressUser['zip_code']).' '.htmlspecialchars($addressUser['city']) ?></p>
                    <p><?= htmlspecialchars($addressUser['country']) ?></p>
                    <p><?= htmlspecialchars($addressUser['phone']) ?></p>
                    <p><?= htmlspecialchars($addressUser['email']) ?></p>
                </address>
            </div>
            <div class="row">
                <div class="table-responsive history-order">
                    <table>
                        <thead>
                            <tr>
                                <th>Désignation produit</th>                                
                                <th>Quantité</th>
                                <th>Prix unitaire</th>
                                <th>Prix total</th>
                            </tr>
                        </thead>
                    <tbody>
                        <?php foreach($order as $detailsOrder) : ?>                    
                            <tr>                        
                                <td>
                                    <?= htmlspecialchars($detailsOrder['history_name_product']) ?>
                                    <span class="product-reference">Référence 
                                        <?= htmlspecialchars($detailsOrder['history_reference_product']) ?>
                                    </span>
                                </td>                        
                                <td><?= htmlspecialchars($detailsOrder['quantity']) ?></td>
                                <td><?= htmlspecialchars($detailsOrder['unit_price_product']) ?> €</td>
                                <td><?= htmlspecialchars(number_format($detailsOrder['quantity'] * $detailsOrder['unit_price_product'],2)) ?> €</td>
                            </tr>                                  
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="total-amount-order" colspan="3">Total de la commande</td>
                            <td><?= htmlspecialchars($detailsOrder['total_amount']) ?> €</td>
                        </tr>                
                    </tfoot>
                </table>                
                </div>
            </div>          
        </div>
    </div>
</article> 
<?php
unset($_SESSION['errors']);
unset($_SESSION['success']);
?>