<?php if(!isset($_SESSION["idUser"])) :
    header('location:../../../../index.php');
    exit();
endif; ?>
<!-- Affichage détails message utilisateur -->
<article>
    <div class="row account-user">
        <h2>Détails de votre message</h2>
        <p>Voici les détails de votre message envoyé au commerçant.</p>
        <nav class="breadcrumb">
            <a class="first" href="index.php" title="Accueil">Accueil</a><span class="chevron">&gt;</span><a href="index.php?page=customer_account" title="Retour à votre espace personnel">Retour à votre espace personnel</a><span class="chevron">&gt;</span><a href="index.php?page=myMessages" title="Retour à vos messages">Retour à vos messages</a><span class="chevron">&gt;</span><span class="current-page">Mes messages</span>
        </nav>        
        <div class="row">
        <p>Fil de discussion #<?= htmlspecialchars($thread) ?></p>
            <div class="table-responsive messages">
                <table>
                    <thead>
                        <tr>
                            <th>Session</th>
                            <th>Date</th>
                            <th>Messages</th>                    
                        </tr>
                    </thead>    
                    <tbody>
                        <?php foreach($detailsMessage as $messages) : ?>                    
                        <tr>
                            <td><?= !empty($messages['id_employee'] == 0) ? '<i class="fas fa-user-circle online"></i>' : '<i class="fas fa-store"></i>' ?></td>                    
                            <td><?= htmlspecialchars($messages['date_add']) ?></td>
                            <td><?= htmlspecialchars($messages['shop_message']) ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>             
                </table>                      
            </div>
        </div>
        <div class="actions">
            <a class="action-button" href="index.php?page=contact" title="Nouveau message">Nouveau message</a>
        </div>
    </div>    
</article>